//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Screen_Text
    {
        public int Id { get; set; }
        public int ScreenId { get; set; }
        public int LanguageId { get; set; }
        public bool IsError { get; set; }
        public string Label { get; set; }
        public string Translation { get; set; }
    
        public virtual App_Screen App_Screen { get; set; }
        public virtual SLanguage SLanguage { get; set; }
    }
}
