//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Media
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int MediaTypeId { get; set; }
        public string FileUrl { get; set; }
        public string Media { get; set; }
        public int OrderNo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SType_Media SType_Media { get; set; }
    }
}
