//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Question_Answer
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int DataTypeId { get; set; }
        public string Answer { get; set; }
        public int OrderNo { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Category_Question Category_Question { get; set; }
        public virtual SType_Data SType_Data { get; set; }
    }
}
