//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category_Question()
        {
            this.Category_Question_Answer = new HashSet<Category_Question_Answer>();
            this.Member_Question_Answer = new HashSet<Member_Question_Answer>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Question { get; set; }
        public string Description { get; set; }
        public int OrderNo { get; set; }
        public int AnswerTypeId { get; set; }
        public bool IsConnected { get; set; }
        public Nullable<int> ConnectedQuestionId { get; set; }
        public Nullable<int> ConnectedAnswerId { get; set; }
        public Nullable<int> AnswerDataTypeId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Question_Answer> Category_Question_Answer { get; set; }
        public virtual SType_QuestionAnswer SType_QuestionAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Question_Answer> Member_Question_Answer { get; set; }
    }
}
