//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Content_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_Content_Detail()
        {
            this.CMS_Content_Detail_Log = new HashSet<CMS_Content_Detail_Log>();
        }
    
        public int Id { get; set; }
        public int ContentId { get; set; }
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public string Abstract { get; set; }
        public string ContentHtml { get; set; }
    
        public virtual CMS_Content CMS_Content { get; set; }
        public virtual SLanguage SLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_Content_Detail_Log> CMS_Content_Detail_Log { get; set; }
    }
}
