//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Content_Detail_Log
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int ContentId { get; set; }
        public int ContentDetailId { get; set; }
        public System.DateTime OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
    
        public virtual CMS_Content CMS_Content { get; set; }
        public virtual CMS_Content_Detail CMS_Content_Detail { get; set; }
        public virtual Member Member { get; set; }
    }
}
