//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Question_Answer
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int CategoryId { get; set; }
        public int QuestionId { get; set; }
        public int AnswerId { get; set; }
        public string Answer { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> ChildId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category_Question Category_Question { get; set; }
        public virtual Member Member { get; set; }
    }
}
