//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Child
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member_Child()
        {
            this.Member_Child_Vaccinate = new HashSet<Member_Child_Vaccinate>();
        }
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string NameSurname { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Vaccine { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Child_Vaccinate> Member_Child_Vaccinate { get; set; }
    }
}
