//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Pregnancy
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string ReminderTitle { get; set; }
        public string ReminderMessage { get; set; }
        public int NotificationId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
