//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Notification
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int NotificationSentId { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Notification_Sent Notification_Sent { get; set; }
    }
}
