//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Sent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification_Sent()
        {
            this.Member_Notification = new HashSet<Member_Notification>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public Nullable<int> NotificationTypeId { get; set; }
        public Nullable<int> NotificationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Notification> Member_Notification { get; set; }
    }
}
