//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.Member_Notification_Log = new HashSet<Member_Notification_Log>();
            this.Notification_Message = new HashSet<Notification_Message>();
        }
    
        public int Id { get; set; }
        public int MinWeek { get; set; }
        public int MaxWeek { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public bool IsWeekly { get; set; }
        public int AfterBirth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Notification_Log> Member_Notification_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification_Message> Notification_Message { get; set; }
        public virtual SType_Notification SType_Notification { get; set; }
    }
}
