//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccinate_Message
    {
        public int Id { get; set; }
        public int VaccinateDetailId { get; set; }
        public int LanguageId { get; set; }
        public string Message { get; set; }
        public bool IsWeekly { get; set; }
    
        public virtual SLanguage SLanguage { get; set; }
        public virtual Vaccinate_Detail Vaccinate_Detail { get; set; }
    }
}
