//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hera.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccinate_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaccinate_Detail()
        {
            this.Vaccinate_Message = new HashSet<Vaccinate_Message>();
        }
    
        public int Id { get; set; }
        public int VaccinateId { get; set; }
        public string Type { get; set; }
        public int Day { get; set; }
    
        public virtual Vaccinate Vaccinate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccinate_Message> Vaccinate_Message { get; set; }
    }
}
